# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KuberoCli < Formula
  desc "Manage your kubero applications with the CLI"
  homepage "https://www.kubero.dev"
  version "1.10.0-beta.4"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubero-dev/kubero-cli/releases/download/v1.10.0-beta.4/kubero-cli_darwin_amd64.tar.gz"
      sha256 "7422a6b141532415eb03959c4f69d21136d591ac37d3318476b6264ea5858ad4"

      def install
        bin.install "kubero"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubero-dev/kubero-cli/releases/download/v1.10.0-beta.4/kubero-cli_darwin_arm64.tar.gz"
      sha256 "f4af24258d31cf5bb5b1df1767e16d4bb2580e08c8004b4c9a28af460d4b854c"

      def install
        bin.install "kubero"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubero-dev/kubero-cli/releases/download/v1.10.0-beta.4/kubero-cli_linux_arm64.tar.gz"
      sha256 "102424a847e8b7e93a86e029219e2085b6bbe66b925f7f7528d559c455e0901e"

      def install
        bin.install "kubero"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kubero-dev/kubero-cli/releases/download/v1.10.0-beta.4/kubero-cli_linux_amd64.tar.gz"
      sha256 "aeeca71a257a6f0fce7574ce9bbb1557b0fa29f067d4a7ef782eb00f5b5b4735"

      def install
        bin.install "kubero"
      end
    end
  end

  test do
    system "#{bin}/kubero", "--version"
  end
end
